# -*- coding: utf-8 -*-
"""WebScrape.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zaDoVp8embfrjWQ6ZnxUjzy3ku75W5Oy

Simple web-scraping program using BeautifulSoup to pull a random quote from [quotes.toscrape.com](https://quotes.toscrape.com)
"""

import random
import requests
from bs4 import BeautifulSoup

# The page we want to scrape. Tests connection
pageNum = random.randint(1, 10)
page = requests.get("https://quotes.toscrape.com/page/" + str(pageNum))
print(page.url)

# Get the HTML content and find all instances where class is quote
soup = BeautifulSoup(page.content, 'html.parser')
quotes = soup.find_all(class_="quote")

# Each page has 10 quotes, generate a random value in this range and pull the quote
randInt = random.randint(0, 9)

quoteText = quotes[randInt].find_all(class_="text")[0].text     # Get the quote from the inner class
quoteAuthor = quotes[randInt].find_all(class_="author")[0].text # Get the Author from the inner class

print(quoteText + '\n' + quoteAuthor)